name: CI

on:
  push:
    branches:
      - master
  pull_request: ~
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build Docker images
        uses: docker/bake-action@v4
        with:
          pull: true
          load: true
          files: |
            compose.yaml
            compose.override.yaml
          set: |
            *.cache-from=type=gha,scope=${{github.ref}}
            *.cache-from=type=gha,scope=refs/heads/master
            *.cache-to=type=gha,scope=${{github.ref}},mode=max
      -
        name: Start services
        run: docker compose up --wait --no-build

      - name: Wait for service
        run: |
          retries=5
          while [ $retries -gt 0 ]; do
            curl --output /dev/null --silent --head --fail http://localhost:80
            retVal=$?
            if [ $retVal -eq 0 ]; then
              echo "Service is up!"
              break
            fi
            echo "Waiting for the service to be up, attempt $((6 - retries))..."
            retries=$((retries - 1))
            sleep 15
          done
          if [ $retries -eq 0 ]; then
            echo "Service did not become ready in time"
            exit 1
          fi
      -
        name: Run tests
        run: docker compose exec -T php composer run-script test-all
      -
        name: Check HTTP reachability
        run: curl -v -o /dev/null http://localhost
      -
        name: Run PHPUnit
        if: false # Remove this line if PHPUnit is installed
        run: docker compose exec -T php bin/phpunit
  lint:
    name: Docker Lint
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0